export const states = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const LGAs = [
  { value: "Aba North_Abia", label: "Aba North, Abia" },
  { value: "Aba South_Abia", label: "Aba South, Abia" },
  { value: "Arochukwu_Abia", label: "Arochukwu, Abia" },
  { value: "Bende_Abia", label: "Bende, Abia" },
  { value: "Ikwuano_Abia", label: "Ikwuano, Abia" },
  { value: "Isiala-Ngwa North_Abia", label: "Isiala-Ngwa North, Abia" },
  { value: "Isiala-Ngwa South_Abia", label: "Isiala-Ngwa South, Abia" },
  { value: "Isuikwato_Abia", label: "Isuikwato, Abia" },
  { value: "Obi Nwa_Abia", label: "Obi Nwa, Abia" },
  { value: "Ohafia_Abia", label: "Ohafia, Abia" },
  { value: "Osisioma_Abia", label: "Osisioma, Abia" },
  { value: "Ngwa_Abia", label: "Ngwa, Abia" },
  { value: "Ugwunagbo_Abia", label: "Ugwunagbo, Abia" },
  { value: "Ukwa East_Abia", label: "Ukwa East, Abia" },
  { value: "Ukwa West_Abia", label: "Ukwa West, Abia" },
  { value: "Umuahia North_Abia", label: "Umuahia North, Abia" },
  { value: "Umuahia South_Abia", label: "Umuahia South, Abia" },
  { value: "Umu-Neochi_Abia", label: "Umu-Neochi, Abia" },
  { value: "Demsa_Adamawa", label: "Demsa, Adamawa" },
  { value: "Fufore_Adamawa", label: "Fufore, Adamawa" },
  { value: "Ganaye_Adamawa", label: "Ganaye, Adamawa" },
  { value: "Gireri_Adamawa", label: "Gireri, Adamawa" },
  { value: "Gombi_Adamawa", label: "Gombi, Adamawa" },
  { value: "Guyuk_Adamawa", label: "Guyuk, Adamawa" },
  { value: "Hong_Adamawa", label: "Hong, Adamawa" },
  { value: "Jada_Adamawa", label: "Jada, Adamawa" },
  { value: "Lamurde_Adamawa", label: "Lamurde, Adamawa" },
  { value: "Madagali_Adamawa", label: "Madagali, Adamawa" },
  { value: "Maiha_Adamawa", label: "Maiha, Adamawa" },
  { value: "Mayo-Belwa_Adamawa", label: "Mayo-Belwa, Adamawa" },
  { value: "Michika_Adamawa", label: "Michika, Adamawa" },
  { value: "Mubi North_Adamawa", label: "Mubi North, Adamawa" },
  { value: "Mubi South_Adamawa", label: "Mubi South, Adamawa" },
  { value: "Numan_Adamawa", label: "Numan, Adamawa" },
  { value: "Shelleng_Adamawa", label: "Shelleng, Adamawa" },
  { value: "Song_Adamawa", label: "Song, Adamawa" },
  { value: "Toungo_Adamawa", label: "Toungo, Adamawa" },
  { value: "Yola North_Adamawa", label: "Yola North, Adamawa" },
  { value: "Yola South_Adamawa", label: "Yola South, Adamawa" },
  { value: "Aguata_Anambra", label: "Aguata, Anambra" },
  { value: "Anambra East_Anambra", label: "Anambra East, Anambra" },
  { value: "Anambra West_Anambra", label: "Anambra West, Anambra" },
  { value: "Anaocha_Anambra", label: "Anaocha, Anambra" },
  { value: "Awka North_Anambra", label: "Awka North, Anambra" },
  { value: "Awka South_Anambra", label: "Awka South, Anambra" },
  { value: "Ayamelum_Anambra", label: "Ayamelum, Anambra" },
  { value: "Dunukofia_Anambra", label: "Dunukofia, Anambra" },
  { value: "Ekwusigo_Anambra", label: "Ekwusigo, Anambra" },
  { value: "Idemili North_Anambra", label: "Idemili North, Anambra" },
  { value: "Idemili south_Anambra", label: "Idemili south, Anambra" },
  { value: "Ihiala_Anambra", label: "Ihiala, Anambra" },
  { value: "Njikoka_Anambra", label: "Njikoka, Anambra" },
  { value: "Nnewi North_Anambra", label: "Nnewi North, Anambra" },
  { value: "Nnewi South_Anambra", label: "Nnewi South, Anambra" },
  { value: "Ogbaru_Anambra", label: "Ogbaru, Anambra" },
  { value: "Onitsha North_Anambra", label: "Onitsha North, Anambra" },
  { value: "Onitsha South_Anambra", label: "Onitsha South, Anambra" },
  { value: "Orumba North_Anambra", label: "Orumba North, Anambra" },
  { value: "Orumba South_Anambra", label: "Orumba South, Anambra" },
  { value: "Oyi_Anambra", label: "Oyi, Anambra" },
  { value: "Abak_Akwa Ibom", label: "Abak, Akwa Ibom" },
  { value: "Eastern Obolo_Akwa Ibom", label: "Eastern Obolo, Akwa Ibom" },
  { value: "Eket_Akwa Ibom", label: "Eket, Akwa Ibom" },
  { value: "Esit Eket_Akwa Ibom", label: "Esit Eket, Akwa Ibom" },
  { value: "Essien Udim_Akwa Ibom", label: "Essien Udim, Akwa Ibom" },
  { value: "Etim Ekpo_Akwa Ibom", label: "Etim Ekpo, Akwa Ibom" },
  { value: "Etinan_Akwa Ibom", label: "Etinan, Akwa Ibom" },
  { value: "Ibeno_Akwa Ibom", label: "Ibeno, Akwa Ibom" },
  { value: "Ibesikpo Asutan_Akwa Ibom", label: "Ibesikpo Asutan, Akwa Ibom" },
  { value: "Ibiono Ibom_Akwa Ibom", label: "Ibiono Ibom, Akwa Ibom" },
  { value: "Ika_Akwa Ibom", label: "Ika, Akwa Ibom" },
  { value: "Ikono_Akwa Ibom", label: "Ikono, Akwa Ibom" },
  { value: "Ikot Abasi_Akwa Ibom", label: "Ikot Abasi, Akwa Ibom" },
  { value: "Ikot Ekpene_Akwa Ibom", label: "Ikot Ekpene, Akwa Ibom" },
  { value: "Ini_Akwa Ibom", label: "Ini, Akwa Ibom" },
  { value: "Itu_Akwa Ibom", label: "Itu, Akwa Ibom" },
  { value: "Mbo_Akwa Ibom", label: "Mbo, Akwa Ibom" },
  { value: "Mkpat Enin_Akwa Ibom", label: "Mkpat Enin, Akwa Ibom" },
  { value: "Nsit Atai_Akwa Ibom", label: "Nsit Atai, Akwa Ibom" },
  { value: "Nsit Ibom_Akwa Ibom", label: "Nsit Ibom, Akwa Ibom" },
  { value: "Nsit Ubium_Akwa Ibom", label: "Nsit Ubium, Akwa Ibom" },
  { value: "Obot Akara_Akwa Ibom", label: "Obot Akara, Akwa Ibom" },
  { value: "Okobo_Akwa Ibom", label: "Okobo, Akwa Ibom" },
  { value: "Onna_Akwa Ibom", label: "Onna, Akwa Ibom" },
  { value: "Oron_Akwa Ibom", label: "Oron, Akwa Ibom" },
  { value: "Oruk Anam_Akwa Ibom", label: "Oruk Anam, Akwa Ibom" },
  { value: "Udung Uko_Akwa Ibom", label: "Udung Uko, Akwa Ibom" },
  { value: "Ukanafun_Akwa Ibom", label: "Ukanafun, Akwa Ibom" },
  { value: "Uruan_Akwa Ibom", label: "Uruan, Akwa Ibom" },
  {
    value: "Urue-Offong/Oruko _Akwa Ibom",
    label: "Urue-Offong/Oruko , Akwa Ibom",
  },
  { value: "Uyo_Akwa Ibom", label: "Uyo, Akwa Ibom" },
  { value: "Alkaleri_Bauchi", label: "Alkaleri, Bauchi" },
  { value: "Bauchi_Bauchi", label: "Bauchi, Bauchi" },
  { value: "Bogoro_Bauchi", label: "Bogoro, Bauchi" },
  { value: "Damban_Bauchi", label: "Damban, Bauchi" },
  { value: "Darazo_Bauchi", label: "Darazo, Bauchi" },
  { value: "Dass_Bauchi", label: "Dass, Bauchi" },
  { value: "Ganjuwa_Bauchi", label: "Ganjuwa, Bauchi" },
  { value: "Giade_Bauchi", label: "Giade, Bauchi" },
  { value: "Itas/Gadau_Bauchi", label: "Itas/Gadau, Bauchi" },
  { value: "Jama'are_Bauchi", label: "Jama'are, Bauchi" },
  { value: "Katagum_Bauchi", label: "Katagum, Bauchi" },
  { value: "Kirfi_Bauchi", label: "Kirfi, Bauchi" },
  { value: "Misau_Bauchi", label: "Misau, Bauchi" },
  { value: "Ningi_Bauchi", label: "Ningi, Bauchi" },
  { value: "Shira_Bauchi", label: "Shira, Bauchi" },
  { value: "Tafawa-Balewa_Bauchi", label: "Tafawa-Balewa, Bauchi" },
  { value: "Toro_Bauchi", label: "Toro, Bauchi" },
  { value: "Warji_Bauchi", label: "Warji, Bauchi" },
  { value: "Zaki_Bauchi", label: "Zaki, Bauchi" },
  { value: "Brass_Bayelsa", label: "Brass, Bayelsa" },
  { value: "Ekeremor_Bayelsa", label: "Ekeremor, Bayelsa" },
  { value: "Kolokuma/Opokuma_Bayelsa", label: "Kolokuma/Opokuma, Bayelsa" },
  { value: "Nembe_Bayelsa", label: "Nembe, Bayelsa" },
  { value: "Ogbia_Bayelsa", label: "Ogbia, Bayelsa" },
  { value: "Sagbama_Bayelsa", label: "Sagbama, Bayelsa" },
  { value: "Southern Jaw_Bayelsa", label: "Southern Jaw, Bayelsa" },
  { value: "Yenegoa_Bayelsa", label: "Yenegoa, Bayelsa" },
  { value: "Ado_Benue", label: "Ado, Benue" },
  { value: "Agatu_Benue", label: "Agatu, Benue" },
  { value: "Apa_Benue", label: "Apa, Benue" },
  { value: "Buruku_Benue", label: "Buruku, Benue" },
  { value: "Gboko_Benue", label: "Gboko, Benue" },
  { value: "Guma_Benue", label: "Guma, Benue" },
  { value: "Gwer East_Benue", label: "Gwer East, Benue" },
  { value: "Gwer West_Benue", label: "Gwer West, Benue" },
  { value: "Katsina-Ala_Benue", label: "Katsina-Ala, Benue" },
  { value: "Konshisha_Benue", label: "Konshisha, Benue" },
  { value: "Kwande_Benue", label: "Kwande, Benue" },
  { value: "Logo_Benue", label: "Logo, Benue" },
  { value: "Makurdi_Benue", label: "Makurdi, Benue" },
  { value: "Obi_Benue", label: "Obi, Benue" },
  { value: "Ogbadibo_Benue", label: "Ogbadibo, Benue" },
  { value: "Oju_Benue", label: "Oju, Benue" },
  { value: "Okpokwu_Benue", label: "Okpokwu, Benue" },
  { value: "Ohimini_Benue", label: "Ohimini, Benue" },
  { value: "Oturkpo_Benue", label: "Oturkpo, Benue" },
  { value: "Tarka_Benue", label: "Tarka, Benue" },
  { value: "Ukum_Benue", label: "Ukum, Benue" },
  { value: "Ushongo_Benue", label: "Ushongo, Benue" },
  { value: "Vandeikya_Benue", label: "Vandeikya, Benue" },
  { value: "Abadam_Borno", label: "Abadam, Borno" },
  { value: "Askira/Uba_Borno", label: "Askira/Uba, Borno" },
  { value: "Bama_Borno", label: "Bama, Borno" },
  { value: "Bayo_Borno", label: "Bayo, Borno" },
  { value: "Biu_Borno", label: "Biu, Borno" },
  { value: "Chibok_Borno", label: "Chibok, Borno" },
  { value: "Damboa_Borno", label: "Damboa, Borno" },
  { value: "Dikwa_Borno", label: "Dikwa, Borno" },
  { value: "Gubio_Borno", label: "Gubio, Borno" },
  { value: "Guzamala_Borno", label: "Guzamala, Borno" },
  { value: "Gwoza_Borno", label: "Gwoza, Borno" },
  { value: "Hawul_Borno", label: "Hawul, Borno" },
  { value: "Jere_Borno", label: "Jere, Borno" },
  { value: "Kaga_Borno", label: "Kaga, Borno" },
  { value: "Kala/Balge_Borno", label: "Kala/Balge, Borno" },
  { value: "Konduga_Borno", label: "Konduga, Borno" },
  { value: "Kukawa_Borno", label: "Kukawa, Borno" },
  { value: "Kwaya Kusar_Borno", label: "Kwaya Kusar, Borno" },
  { value: "Mafa_Borno", label: "Mafa, Borno" },
  { value: "Magumeri_Borno", label: "Magumeri, Borno" },
  { value: "Maiduguri_Borno", label: "Maiduguri, Borno" },
  { value: "Marte_Borno", label: "Marte, Borno" },
  { value: "Mobbar_Borno", label: "Mobbar, Borno" },
  { value: "Monguno_Borno", label: "Monguno, Borno" },
  { value: "Ngala_Borno", label: "Ngala, Borno" },
  { value: "Nganzai_Borno", label: "Nganzai, Borno" },
  { value: "Shani_Borno", label: "Shani, Borno" },
  { value: "Akpabuyo_Cross River", label: "Akpabuyo, Cross River" },
  { value: "Odukpani_Cross River", label: "Odukpani, Cross River" },
  { value: "Akamkpa_Cross River", label: "Akamkpa, Cross River" },
  { value: "Biase_Cross River", label: "Biase, Cross River" },
  { value: "Abi_Cross River", label: "Abi, Cross River" },
  { value: "Ikom_Cross River", label: "Ikom, Cross River" },
  { value: "Yarkur_Cross River", label: "Yarkur, Cross River" },
  { value: "Odubra_Cross River", label: "Odubra, Cross River" },
  { value: "Boki_Cross River", label: "Boki, Cross River" },
  { value: "Ogoja_Cross River", label: "Ogoja, Cross River" },
  { value: "Yala_Cross River", label: "Yala, Cross River" },
  { value: "Obanliku_Cross River", label: "Obanliku, Cross River" },
  { value: "Obudu_Cross River", label: "Obudu, Cross River" },
  { value: "Calabar South_Cross River", label: "Calabar South, Cross River" },
  { value: "Etung_Cross River", label: "Etung, Cross River" },
  { value: "Bekwara_Cross River", label: "Bekwara, Cross River" },
  { value: "Bakassi_Cross River", label: "Bakassi, Cross River" },
  {
    value: "Calabar Municipality_Cross River",
    label: "Calabar Municipality, Cross River",
  },
  { value: "Oshimili_Delta", label: "Oshimili, Delta" },
  { value: "Aniocha_Delta", label: "Aniocha, Delta" },
  { value: "Aniocha South_Delta", label: "Aniocha South, Delta" },
  { value: "Ika South_Delta", label: "Ika South, Delta" },
  { value: "Ika North-East_Delta", label: "Ika North-East, Delta" },
  { value: "Ndokwa West_Delta", label: "Ndokwa West, Delta" },
  { value: "Ndokwa East_Delta", label: "Ndokwa East, Delta" },
  { value: "Isoko south_Delta", label: "Isoko south, Delta" },
  { value: "Isoko North_Delta", label: "Isoko North, Delta" },
  { value: "Bomadi_Delta", label: "Bomadi, Delta" },
  { value: "Burutu_Delta", label: "Burutu, Delta" },
  { value: "Ughelli South_Delta", label: "Ughelli South, Delta" },
  { value: "Ughelli North_Delta", label: "Ughelli North, Delta" },
  { value: "Ethiope West_Delta", label: "Ethiope West, Delta" },
  { value: "Ethiope East_Delta", label: "Ethiope East, Delta" },
  { value: "Sapele_Delta", label: "Sapele, Delta" },
  { value: "Okpe_Delta", label: "Okpe, Delta" },
  { value: "Warri North_Delta", label: "Warri North, Delta" },
  { value: "Warri South_Delta", label: "Warri South, Delta" },
  { value: "Uvwie_Delta", label: "Uvwie, Delta" },
  { value: "Udu_Delta", label: "Udu, Delta" },
  { value: "Warri Central_Delta", label: "Warri Central, Delta" },
  { value: "Ukwani_Delta", label: "Ukwani, Delta" },
  { value: "Oshimili North_Delta", label: "Oshimili North, Delta" },
  { value: "Patani_Delta", label: "Patani, Delta" },
  { value: "Edda_Ebonyi", label: "Edda, Ebonyi" },
  { value: "Afikpo_Ebonyi", label: "Afikpo, Ebonyi" },
  { value: "Onicha_Ebonyi", label: "Onicha, Ebonyi" },
  { value: "Ohaozara_Ebonyi", label: "Ohaozara, Ebonyi" },
  { value: "Abakaliki_Ebonyi", label: "Abakaliki, Ebonyi" },
  { value: "Ishielu_Ebonyi", label: "Ishielu, Ebonyi" },
  { value: "lkwo_Ebonyi", label: "lkwo, Ebonyi" },
  { value: "Ezza_Ebonyi", label: "Ezza, Ebonyi" },
  { value: "Ezza South_Ebonyi", label: "Ezza South, Ebonyi" },
  { value: "Ohaukwu_Ebonyi", label: "Ohaukwu, Ebonyi" },
  { value: "Ebonyi_Ebonyi", label: "Ebonyi, Ebonyi" },
  { value: "Ivo_Ebonyi", label: "Ivo, Ebonyi" },
  { value: "Enugu South,_Enugu", label: "Enugu South,, Enugu" },
  { value: "Igbo-Eze South_Enugu", label: "Igbo-Eze South, Enugu" },
  { value: "Enugu North_Enugu", label: "Enugu North, Enugu" },
  { value: "Nkanu_Enugu", label: "Nkanu, Enugu" },
  { value: "Udi Agwu_Enugu", label: "Udi Agwu, Enugu" },
  { value: "Oji-River_Enugu", label: "Oji-River, Enugu" },
  { value: "Ezeagu_Enugu", label: "Ezeagu, Enugu" },
  { value: "IgboEze North_Enugu", label: "IgboEze North, Enugu" },
  { value: "Isi-Uzo_Enugu", label: "Isi-Uzo, Enugu" },
  { value: "Nsukka_Enugu", label: "Nsukka, Enugu" },
  { value: "Igbo-Ekiti_Enugu", label: "Igbo-Ekiti, Enugu" },
  { value: "Uzo-Uwani_Enugu", label: "Uzo-Uwani, Enugu" },
  { value: "Enugu Eas_Enugu", label: "Enugu Eas, Enugu" },
  { value: "Aninri_Enugu", label: "Aninri, Enugu" },
  { value: "Nkanu East_Enugu", label: "Nkanu East, Enugu" },
  { value: "Udenu._Enugu", label: "Udenu., Enugu" },
  { value: "Esan North-East_Edo", label: "Esan North-East, Edo" },
  { value: "Esan Central_Edo", label: "Esan Central, Edo" },
  { value: "Esan West_Edo", label: "Esan West, Edo" },
  { value: "Egor_Edo", label: "Egor, Edo" },
  { value: "Ukpoba_Edo", label: "Ukpoba, Edo" },
  { value: "Central_Edo", label: "Central, Edo" },
  { value: "Etsako Central_Edo", label: "Etsako Central, Edo" },
  { value: "Igueben_Edo", label: "Igueben, Edo" },
  { value: "Oredo_Edo", label: "Oredo, Edo" },
  { value: "Ovia SouthWest_Edo", label: "Ovia SouthWest, Edo" },
  { value: "Ovia South-East_Edo", label: "Ovia South-East, Edo" },
  { value: "Orhionwon_Edo", label: "Orhionwon, Edo" },
  { value: "Uhunmwonde_Edo", label: "Uhunmwonde, Edo" },
  { value: "Etsako East_Edo", label: "Etsako East, Edo" },
  { value: "Esan South-East_Edo", label: "Esan South-East, Edo" },
  { value: "Ado_Ekiti", label: "Ado, Ekiti" },
  { value: "Ekiti-East_Ekiti", label: "Ekiti-East, Ekiti" },
  { value: "Ekiti-West_Ekiti", label: "Ekiti-West, Ekiti" },
  { value: "Emure/Ise/Orun_Ekiti", label: "Emure/Ise/Orun, Ekiti" },
  { value: "Ekiti South-West_Ekiti", label: "Ekiti South-West, Ekiti" },
  { value: "Ikere_Ekiti", label: "Ikere, Ekiti" },
  { value: "Irepodun_Ekiti", label: "Irepodun, Ekiti" },
  { value: "Ijero,_Ekiti", label: "Ijero,, Ekiti" },
  { value: "Ido/Osi_Ekiti", label: "Ido/Osi, Ekiti" },
  { value: "Oye_Ekiti", label: "Oye, Ekiti" },
  { value: "Ikole_Ekiti", label: "Ikole, Ekiti" },
  { value: "Moba_Ekiti", label: "Moba, Ekiti" },
  { value: "Gbonyin_Ekiti", label: "Gbonyin, Ekiti" },
  { value: "Efon_Ekiti", label: "Efon, Ekiti" },
  { value: "Ise/Orun_Ekiti", label: "Ise/Orun, Ekiti" },
  { value: "Ilejemeje._Ekiti", label: "Ilejemeje., Ekiti" },
  { value: "Abaji_FCT", label: "Abaji, FCT" },
  { value: "Abuja Municipal_FCT", label: "Abuja Municipal, FCT" },
  { value: "Bwari_FCT", label: "Bwari, FCT" },
  { value: "Gwagwalada_FCT", label: "Gwagwalada, FCT" },
  { value: "Kuje_FCT", label: "Kuje, FCT" },
  { value: "Kwali_FCT", label: "Kwali, FCT" },
  { value: "Akko_Gombe", label: "Akko, Gombe" },
  { value: "Balanga_Gombe", label: "Balanga, Gombe" },
  { value: "Billiri_Gombe", label: "Billiri, Gombe" },
  { value: "Dukku_Gombe", label: "Dukku, Gombe" },
  { value: "Kaltungo_Gombe", label: "Kaltungo, Gombe" },
  { value: "Kwami_Gombe", label: "Kwami, Gombe" },
  { value: "Shomgom_Gombe", label: "Shomgom, Gombe" },
  { value: "Funakaye_Gombe", label: "Funakaye, Gombe" },
  { value: "Gombe_Gombe", label: "Gombe, Gombe" },
  { value: "Nafada/Bajoga_Gombe", label: "Nafada/Bajoga, Gombe" },
  { value: "Yamaltu/Delta._Gombe", label: "Yamaltu/Delta., Gombe" },
  { value: "Aboh-Mbaise_Imo", label: "Aboh-Mbaise, Imo" },
  { value: "Ahiazu-Mbaise_Imo", label: "Ahiazu-Mbaise, Imo" },
  { value: "Ehime-Mbano_Imo", label: "Ehime-Mbano, Imo" },
  { value: "Ezinihitte_Imo", label: "Ezinihitte, Imo" },
  { value: "Ideato North_Imo", label: "Ideato North, Imo" },
  { value: "Ideato South_Imo", label: "Ideato South, Imo" },
  { value: "Ihitte/Uboma_Imo", label: "Ihitte/Uboma, Imo" },
  { value: "Ikeduru_Imo", label: "Ikeduru, Imo" },
  { value: "Isiala Mbano_Imo", label: "Isiala Mbano, Imo" },
  { value: "Isu_Imo", label: "Isu, Imo" },
  { value: "Mbaitoli_Imo", label: "Mbaitoli, Imo" },
  { value: "Ngor-Okpala_Imo", label: "Ngor-Okpala, Imo" },
  { value: "Njaba_Imo", label: "Njaba, Imo" },
  { value: "Nwangele_Imo", label: "Nwangele, Imo" },
  { value: "Nkwerre_Imo", label: "Nkwerre, Imo" },
  { value: "Obowo_Imo", label: "Obowo, Imo" },
  { value: "Oguta_Imo", label: "Oguta, Imo" },
  { value: "Ohaji/Egbema_Imo", label: "Ohaji/Egbema, Imo" },
  { value: "Okigwe_Imo", label: "Okigwe, Imo" },
  { value: "Orlu_Imo", label: "Orlu, Imo" },
  { value: "Orsu_Imo", label: "Orsu, Imo" },
  { value: "Oru East_Imo", label: "Oru East, Imo" },
  { value: "Oru West_Imo", label: "Oru West, Imo" },
  { value: "Owerri-Municipal_Imo", label: "Owerri-Municipal, Imo" },
  { value: "Owerri North_Imo", label: "Owerri North, Imo" },
  { value: "Owerri West_Imo", label: "Owerri West, Imo" },
  { value: "Auyo_Jigawa", label: "Auyo, Jigawa" },
  { value: "Babura_Jigawa", label: "Babura, Jigawa" },
  { value: "Birni Kudu_Jigawa", label: "Birni Kudu, Jigawa" },
  { value: "Biriniwa_Jigawa", label: "Biriniwa, Jigawa" },
  { value: "Buji_Jigawa", label: "Buji, Jigawa" },
  { value: "Dutse_Jigawa", label: "Dutse, Jigawa" },
  { value: "Gagarawa_Jigawa", label: "Gagarawa, Jigawa" },
  { value: "Garki_Jigawa", label: "Garki, Jigawa" },
  { value: "Gumel_Jigawa", label: "Gumel, Jigawa" },
  { value: "Guri_Jigawa", label: "Guri, Jigawa" },
  { value: "Gwaram_Jigawa", label: "Gwaram, Jigawa" },
  { value: "Gwiwa_Jigawa", label: "Gwiwa, Jigawa" },
  { value: "Hadejia_Jigawa", label: "Hadejia, Jigawa" },
  { value: "Jahun_Jigawa", label: "Jahun, Jigawa" },
  { value: "Kafin Hausa_Jigawa", label: "Kafin Hausa, Jigawa" },
  { value: "Kaugama Kazaure_Jigawa", label: "Kaugama Kazaure, Jigawa" },
  { value: "Kiri Kasamma_Jigawa", label: "Kiri Kasamma, Jigawa" },
  { value: "Kiyawa_Jigawa", label: "Kiyawa, Jigawa" },
  { value: "Maigatari_Jigawa", label: "Maigatari, Jigawa" },
  { value: "Malam Madori_Jigawa", label: "Malam Madori, Jigawa" },
  { value: "Miga_Jigawa", label: "Miga, Jigawa" },
  { value: "Ringim_Jigawa", label: "Ringim, Jigawa" },
  { value: "Roni_Jigawa", label: "Roni, Jigawa" },
  { value: "Sule-Tankarkar_Jigawa", label: "Sule-Tankarkar, Jigawa" },
  { value: "Taura_Jigawa", label: "Taura, Jigawa" },
  { value: "Yankwashi_Jigawa", label: "Yankwashi, Jigawa" },
  { value: "Birni-Gwari_Kaduna", label: "Birni-Gwari, Kaduna" },
  { value: "Chikun_Kaduna", label: "Chikun, Kaduna" },
  { value: "Giwa_Kaduna", label: "Giwa, Kaduna" },
  { value: "Igabi_Kaduna", label: "Igabi, Kaduna" },
  { value: "Ikara_Kaduna", label: "Ikara, Kaduna" },
  { value: "jaba_Kaduna", label: "jaba, Kaduna" },
  { value: "Jema'a_Kaduna", label: "Jema'a, Kaduna" },
  { value: "Kachia_Kaduna", label: "Kachia, Kaduna" },
  { value: "Kaduna North_Kaduna", label: "Kaduna North, Kaduna" },
  { value: "Kaduna South_Kaduna", label: "Kaduna South, Kaduna" },
  { value: "Kagarko_Kaduna", label: "Kagarko, Kaduna" },
  { value: "Kajuru_Kaduna", label: "Kajuru, Kaduna" },
  { value: "Kaura_Kaduna", label: "Kaura, Kaduna" },
  { value: "Kauru_Kaduna", label: "Kauru, Kaduna" },
  { value: "Kubau_Kaduna", label: "Kubau, Kaduna" },
  { value: "Kudan_Kaduna", label: "Kudan, Kaduna" },
  { value: "Lere_Kaduna", label: "Lere, Kaduna" },
  { value: "Makarfi_Kaduna", label: "Makarfi, Kaduna" },
  { value: "Sabon-Gari_Kaduna", label: "Sabon-Gari, Kaduna" },
  { value: "Sanga_Kaduna", label: "Sanga, Kaduna" },
  { value: "Soba_Kaduna", label: "Soba, Kaduna" },
  { value: "Zango-Kataf_Kaduna", label: "Zango-Kataf, Kaduna" },
  { value: "Zaria_Kaduna", label: "Zaria, Kaduna" },
  { value: "Ajingi_Kano", label: "Ajingi, Kano" },
  { value: "Albasu_Kano", label: "Albasu, Kano" },
  { value: "Bagwai_Kano", label: "Bagwai, Kano" },
  { value: "Bebeji_Kano", label: "Bebeji, Kano" },
  { value: "Bichi_Kano", label: "Bichi, Kano" },
  { value: "Bunkure_Kano", label: "Bunkure, Kano" },
  { value: "Dala_Kano", label: "Dala, Kano" },
  { value: "Dambatta_Kano", label: "Dambatta, Kano" },
  { value: "Dawakin Kudu_Kano", label: "Dawakin Kudu, Kano" },
  { value: "Dawakin Tofa_Kano", label: "Dawakin Tofa, Kano" },
  { value: "Doguwa_Kano", label: "Doguwa, Kano" },
  { value: "Fagge_Kano", label: "Fagge, Kano" },
  { value: "Gabasawa_Kano", label: "Gabasawa, Kano" },
  { value: "Garko_Kano", label: "Garko, Kano" },
  { value: "Garum_Kano", label: "Garum, Kano" },
  { value: "Mallam_Kano", label: "Mallam, Kano" },
  { value: "Gaya_Kano", label: "Gaya, Kano" },
  { value: "Gezawa_Kano", label: "Gezawa, Kano" },
  { value: "Gwale_Kano", label: "Gwale, Kano" },
  { value: "Gwarzo_Kano", label: "Gwarzo, Kano" },
  { value: "Kabo_Kano", label: "Kabo, Kano" },
  { value: "Kano Municipal_Kano", label: "Kano Municipal, Kano" },
  { value: "Karaye_Kano", label: "Karaye, Kano" },
  { value: "Kibiya_Kano", label: "Kibiya, Kano" },
  { value: "Kiru_Kano", label: "Kiru, Kano" },
  { value: "kumbotso_Kano", label: "kumbotso, Kano" },
  { value: "Ghari_Kano", label: "Ghari, Kano" },
  { value: "Kura_Kano", label: "Kura, Kano" },
  { value: "Madobi_Kano", label: "Madobi, Kano" },
  { value: "Makoda_Kano", label: "Makoda, Kano" },
  { value: "Minjibir_Kano", label: "Minjibir, Kano" },
  { value: "Nasarawa_Kano", label: "Nasarawa, Kano" },
  { value: "Rano_Kano", label: "Rano, Kano" },
  { value: "Rimin Gado_Kano", label: "Rimin Gado, Kano" },
  { value: "Rogo_Kano", label: "Rogo, Kano" },
  { value: "Shanono_Kano", label: "Shanono, Kano" },
  { value: "Sumaila_Kano", label: "Sumaila, Kano" },
  { value: "Takali_Kano", label: "Takali, Kano" },
  { value: "Tarauni_Kano", label: "Tarauni, Kano" },
  { value: "Tofa_Kano", label: "Tofa, Kano" },
  { value: "Tsanyawa_Kano", label: "Tsanyawa, Kano" },
  { value: "Tudun Wada_Kano", label: "Tudun Wada, Kano" },
  { value: "Ungogo_Kano", label: "Ungogo, Kano" },
  { value: "Warawa_Kano", label: "Warawa, Kano" },
  { value: "Wudil_Kano", label: "Wudil, Kano" },
  { value: "Bakori_Katsina", label: "Bakori, Katsina" },
  { value: "Batagarawa_Katsina", label: "Batagarawa, Katsina" },
  { value: "Batsari_Katsina", label: "Batsari, Katsina" },
  { value: "Baure_Katsina", label: "Baure, Katsina" },
  { value: "Bindawa_Katsina", label: "Bindawa, Katsina" },
  { value: "Charanchi_Katsina", label: "Charanchi, Katsina" },
  { value: "Dandume_Katsina", label: "Dandume, Katsina" },
  { value: "Danja_Katsina", label: "Danja, Katsina" },
  { value: "Dan Musa_Katsina", label: "Dan Musa, Katsina" },
  { value: "Daura_Katsina", label: "Daura, Katsina" },
  { value: "Dutsi_Katsina", label: "Dutsi, Katsina" },
  { value: "Dutsin-Ma_Katsina", label: "Dutsin-Ma, Katsina" },
  { value: "Faskari_Katsina", label: "Faskari, Katsina" },
  { value: "Funtua_Katsina", label: "Funtua, Katsina" },
  { value: "Ingawa_Katsina", label: "Ingawa, Katsina" },
  { value: "Jibia_Katsina", label: "Jibia, Katsina" },
  { value: "Kafur_Katsina", label: "Kafur, Katsina" },
  { value: "Kaita_Katsina", label: "Kaita, Katsina" },
  { value: "Kankara_Katsina", label: "Kankara, Katsina" },
  { value: "Kankia_Katsina", label: "Kankia, Katsina" },
  { value: "Katsina_Katsina", label: "Katsina, Katsina" },
  { value: "Kurfi_Katsina", label: "Kurfi, Katsina" },
  { value: "Kusada_Katsina", label: "Kusada, Katsina" },
  { value: "Mai'Adua_Katsina", label: "Mai'Adua, Katsina" },
  { value: "Malumfashi_Katsina", label: "Malumfashi, Katsina" },
  { value: "Mani_Katsina", label: "Mani, Katsina" },
  { value: "Mashi_Katsina", label: "Mashi, Katsina" },
  { value: "Matazuu_Katsina", label: "Matazuu, Katsina" },
  { value: "Musawa_Katsina", label: "Musawa, Katsina" },
  { value: "Rimi_Katsina", label: "Rimi, Katsina" },
  { value: "Sabuwa_Katsina", label: "Sabuwa, Katsina" },
  { value: "Safana_Katsina", label: "Safana, Katsina" },
  { value: "Sandamu_Katsina", label: "Sandamu, Katsina" },
  { value: "Zango_Katsina", label: "Zango, Katsina" },
  { value: "Aleiro_Kebbi", label: "Aleiro, Kebbi" },
  { value: "Arewa-Dandi_Kebbi", label: "Arewa-Dandi, Kebbi" },
  { value: "Argungu_Kebbi", label: "Argungu, Kebbi" },
  { value: "Augie_Kebbi", label: "Augie, Kebbi" },
  { value: "Bagudo_Kebbi", label: "Bagudo, Kebbi" },
  { value: "Birnin Kebbi_Kebbi", label: "Birnin Kebbi, Kebbi" },
  { value: "Bunza_Kebbi", label: "Bunza, Kebbi" },
  { value: "Dandi_Kebbi", label: "Dandi, Kebbi" },
  { value: "Fakai_Kebbi", label: "Fakai, Kebbi" },
  { value: "Gwandu_Kebbi", label: "Gwandu, Kebbi" },
  { value: "Jega_Kebbi", label: "Jega, Kebbi" },
  { value: "Kalgo_Kebbi", label: "Kalgo, Kebbi" },
  { value: "Koko/Besse_Kebbi", label: "Koko/Besse, Kebbi" },
  { value: "Maiyama_Kebbi", label: "Maiyama, Kebbi" },
  { value: "Ngaski_Kebbi", label: "Ngaski, Kebbi" },
  { value: "Sakaba_Kebbi", label: "Sakaba, Kebbi" },
  { value: "Shanga_Kebbi", label: "Shanga, Kebbi" },
  { value: "Suru_Kebbi", label: "Suru, Kebbi" },
  { value: "Wasagu/Danko_Kebbi", label: "Wasagu/Danko, Kebbi" },
  { value: "Yauri_Kebbi", label: "Yauri, Kebbi" },
  { value: "Zuru_Kebbi", label: "Zuru, Kebbi" },
  { value: "Adavi_Kogi", label: "Adavi, Kogi" },
  { value: "Ajaokuta_Kogi", label: "Ajaokuta, Kogi" },
  { value: "Ankpa_Kogi", label: "Ankpa, Kogi" },
  { value: "Bassa_Kogi", label: "Bassa, Kogi" },
  { value: "Dekina_Kogi", label: "Dekina, Kogi" },
  { value: "Ibaji_Kogi", label: "Ibaji, Kogi" },
  { value: "Idah_Kogi", label: "Idah, Kogi" },
  { value: "Igalamela-Odolu_Kogi", label: "Igalamela-Odolu, Kogi" },
  { value: "Ijumu_Kogi", label: "Ijumu, Kogi" },
  { value: "Kabba/Bunu_Kogi", label: "Kabba/Bunu, Kogi" },
  { value: "Kogi_Kogi", label: "Kogi, Kogi" },
  { value: "Lokoja_Kogi", label: "Lokoja, Kogi" },
  { value: "Mopa-Muro_Kogi", label: "Mopa-Muro, Kogi" },
  { value: "Ofu_Kogi", label: "Ofu, Kogi" },
  { value: "Ogori/Mangongo_Kogi", label: "Ogori/Mangongo, Kogi" },
  { value: "Okehi_Kogi", label: "Okehi, Kogi" },
  { value: "Okene_Kogi", label: "Okene, Kogi" },
  { value: "Olamabolo_Kogi", label: "Olamabolo, Kogi" },
  { value: "Omala_Kogi", label: "Omala, Kogi" },
  { value: "Yagba East_Kogi", label: "Yagba East, Kogi" },
  { value: "Yagba West_Kogi", label: "Yagba West, Kogi" },
  { value: "Asa_Kwara", label: "Asa, Kwara" },
  { value: "Baruten_Kwara", label: "Baruten, Kwara" },
  { value: "Edu_Kwara", label: "Edu, Kwara" },
  { value: "Ekiti_Kwara", label: "Ekiti, Kwara" },
  { value: "Ifelodun_Kwara", label: "Ifelodun, Kwara" },
  { value: "Ilorin East_Kwara", label: "Ilorin East, Kwara" },
  { value: "Ilorin West_Kwara", label: "Ilorin West, Kwara" },
  { value: "Irepodun_Kwara", label: "Irepodun, Kwara" },
  { value: "Isin_Kwara", label: "Isin, Kwara" },
  { value: "Kaiama_Kwara", label: "Kaiama, Kwara" },
  { value: "Moro_Kwara", label: "Moro, Kwara" },
  { value: "Offa_Kwara", label: "Offa, Kwara" },
  { value: "Oke-Ero_Kwara", label: "Oke-Ero, Kwara" },
  { value: "Oyun_Kwara", label: "Oyun, Kwara" },
  { value: "Pategi_Kwara", label: "Pategi, Kwara" },
  { value: "Agege_Lagos", label: "Agege, Lagos" },
  { value: "Ajeromi-Ifelodun_Lagos", label: "Ajeromi-Ifelodun, Lagos" },
  { value: "Alimosho_Lagos", label: "Alimosho, Lagos" },
  { value: "Amuwo-Odofin_Lagos", label: "Amuwo-Odofin, Lagos" },
  { value: "Apapa_Lagos", label: "Apapa, Lagos" },
  { value: "Badagry_Lagos", label: "Badagry, Lagos" },
  { value: "Epe_Lagos", label: "Epe, Lagos" },
  { value: "Eti-Osa_Lagos", label: "Eti-Osa, Lagos" },
  { value: "Ibeju/Lekki_Lagos", label: "Ibeju/Lekki, Lagos" },
  { value: "Ifako-Ijaye_Lagos", label: "Ifako-Ijaye, Lagos" },
  { value: "Ikeja_Lagos", label: "Ikeja, Lagos" },
  { value: "Ikorodu_Lagos", label: "Ikorodu, Lagos" },
  { value: "Kosofe_Lagos", label: "Kosofe, Lagos" },
  { value: "Lagos Island_Lagos", label: "Lagos Island, Lagos" },
  { value: "Lagos Mainland_Lagos", label: "Lagos Mainland, Lagos" },
  { value: "Mushin_Lagos", label: "Mushin, Lagos" },
  { value: "Ojo_Lagos", label: "Ojo, Lagos" },
  { value: "Oshodi-Isolo_Lagos", label: "Oshodi-Isolo, Lagos" },
  { value: "Shomolu_Lagos", label: "Shomolu, Lagos" },
  { value: "Surulere_Lagos", label: "Surulere, Lagos" },
  { value: "Akwanga_Nasarawa", label: "Akwanga, Nasarawa" },
  { value: "Awe_Nasarawa", label: "Awe, Nasarawa" },
  { value: "Doma_Nasarawa", label: "Doma, Nasarawa" },
  { value: "Karu_Nasarawa", label: "Karu, Nasarawa" },
  { value: "Keana_Nasarawa", label: "Keana, Nasarawa" },
  { value: "Keffi_Nasarawa", label: "Keffi, Nasarawa" },
  { value: "Kokona_Nasarawa", label: "Kokona, Nasarawa" },
  { value: "Lafia_Nasarawa", label: "Lafia, Nasarawa" },
  { value: "Nasarawa_Nasarawa", label: "Nasarawa, Nasarawa" },
  { value: "Nasarawa-Eggon_Nasarawa", label: "Nasarawa-Eggon, Nasarawa" },
  { value: "Obi_Nasarawa", label: "Obi, Nasarawa" },
  { value: "Toto_Nasarawa", label: "Toto, Nasarawa" },
  { value: "Wamba_Nasarawa", label: "Wamba, Nasarawa" },
  { value: "Agaie_Niger", label: "Agaie, Niger" },
  { value: "Agwara_Niger", label: "Agwara, Niger" },
  { value: "Bida_Niger", label: "Bida, Niger" },
  { value: "Borgu_Niger", label: "Borgu, Niger" },
  { value: "Bosso_Niger", label: "Bosso, Niger" },
  { value: "Chanchaga_Niger", label: "Chanchaga, Niger" },
  { value: "Edati_Niger", label: "Edati, Niger" },
  { value: "Gbako_Niger", label: "Gbako, Niger" },
  { value: "Gurara_Niger", label: "Gurara, Niger" },
  { value: "Katcha_Niger", label: "Katcha, Niger" },
  { value: "Kontagora_Niger", label: "Kontagora, Niger" },
  { value: "Lapai_Niger", label: "Lapai, Niger" },
  { value: "Lavun_Niger", label: "Lavun, Niger" },
  { value: "Magama_Niger", label: "Magama, Niger" },
  { value: "Mariga_Niger", label: "Mariga, Niger" },
  { value: "Mashegu_Niger", label: "Mashegu, Niger" },
  { value: "Mokwa_Niger", label: "Mokwa, Niger" },
  { value: "Muya_Niger", label: "Muya, Niger" },
  { value: "Pailoro_Niger", label: "Pailoro, Niger" },
  { value: "Rafi_Niger", label: "Rafi, Niger" },
  { value: "Rijau_Niger", label: "Rijau, Niger" },
  { value: "Shiroro_Niger", label: "Shiroro, Niger" },
  { value: "Suleja_Niger", label: "Suleja, Niger" },
  { value: "Tafa_Niger", label: "Tafa, Niger" },
  { value: "Wushishi_Niger", label: "Wushishi, Niger" },
  { value: "Abeokuta North_Ogun", label: "Abeokuta North, Ogun" },
  { value: "Abeokuta South_Ogun", label: "Abeokuta South, Ogun" },
  { value: "Ado-Odo/Ota_Ogun", label: "Ado-Odo/Ota, Ogun" },
  { value: "Yewa North_Ogun", label: "Yewa North, Ogun" },
  { value: "Yewa South_Ogun", label: "Yewa South, Ogun" },
  { value: "Ewekoro_Ogun", label: "Ewekoro, Ogun" },
  { value: "Ifo_Ogun", label: "Ifo, Ogun" },
  { value: "Ijebu East_Ogun", label: "Ijebu East, Ogun" },
  { value: "Ijebu North_Ogun", label: "Ijebu North, Ogun" },
  { value: "Ijebu North East_Ogun", label: "Ijebu North East, Ogun" },
  { value: "Ijebu Ode_Ogun", label: "Ijebu Ode, Ogun" },
  { value: "Ikenne_Ogun", label: "Ikenne, Ogun" },
  { value: "Imeko-Afon_Ogun", label: "Imeko-Afon, Ogun" },
  { value: "Ipokia_Ogun", label: "Ipokia, Ogun" },
  { value: "Obafemi-Owode_Ogun", label: "Obafemi-Owode, Ogun" },
  { value: "Ogun Waterside_Ogun", label: "Ogun Waterside, Ogun" },
  { value: "Odeda_Ogun", label: "Odeda, Ogun" },
  { value: "Odogbolu_Ogun", label: "Odogbolu, Ogun" },
  { value: "Remo North_Ogun", label: "Remo North, Ogun" },
  { value: "Shagamu_Ogun", label: "Shagamu, Ogun" },
  { value: "Akoko North East_Ondo", label: "Akoko North East, Ondo" },
  { value: "Akoko North West_Ondo", label: "Akoko North West, Ondo" },
  {
    value: "Akoko South Akure East_Ondo",
    label: "Akoko South Akure East, Ondo",
  },
  { value: "Akoko South West_Ondo", label: "Akoko South West, Ondo" },
  { value: "Akure North_Ondo", label: "Akure North, Ondo" },
  { value: "Akure South_Ondo", label: "Akure South, Ondo" },
  { value: "Ese-Odo_Ondo", label: "Ese-Odo, Ondo" },
  { value: "Idanre_Ondo", label: "Idanre, Ondo" },
  { value: "Ifedore_Ondo", label: "Ifedore, Ondo" },
  { value: "Ilaje_Ondo", label: "Ilaje, Ondo" },
  { value: "Ile-Oluji_Ondo", label: "Ile-Oluji, Ondo" },
  { value: "Okeigbo_Ondo", label: "Okeigbo, Ondo" },
  { value: "Irele_Ondo", label: "Irele, Ondo" },
  { value: "Odigbo_Ondo", label: "Odigbo, Ondo" },
  { value: "Okitipupa_Ondo", label: "Okitipupa, Ondo" },
  { value: "Ondo East_Ondo", label: "Ondo East, Ondo" },
  { value: "Ondo West_Ondo", label: "Ondo West, Ondo" },
  { value: "Ose_Ondo", label: "Ose, Ondo" },
  { value: "Owo_Ondo", label: "Owo, Ondo" },
  { value: "Aiyedade_Osun", label: "Aiyedade, Osun" },
  { value: "Aiyedire_Osun", label: "Aiyedire, Osun" },
  { value: "Atakumosa East_Osun", label: "Atakumosa East, Osun" },
  { value: "Atakumosa West_Osun", label: "Atakumosa West, Osun" },
  { value: "Boluwaduro_Osun", label: "Boluwaduro, Osun" },
  { value: "Boripe_Osun", label: "Boripe, Osun" },
  { value: "Ede North_Osun", label: "Ede North, Osun" },
  { value: "Ede South_Osun", label: "Ede South, Osun" },
  { value: "Egbedore_Osun", label: "Egbedore, Osun" },
  { value: "Ejigbo_Osun", label: "Ejigbo, Osun" },
  { value: "Ife Central_Osun", label: "Ife Central, Osun" },
  { value: "Ife East_Osun", label: "Ife East, Osun" },
  { value: "Ife North_Osun", label: "Ife North, Osun" },
  { value: "Ife South_Osun", label: "Ife South, Osun" },
  { value: "Ifedayo_Osun", label: "Ifedayo, Osun" },
  { value: "Ifelodun_Osun", label: "Ifelodun, Osun" },
  { value: "Ila_Osun", label: "Ila, Osun" },
  { value: "Ilesha East_Osun", label: "Ilesha East, Osun" },
  { value: "Ilesha West_Osun", label: "Ilesha West, Osun" },
  { value: "Irepodun_Osun", label: "Irepodun, Osun" },
  { value: "Irewole_Osun", label: "Irewole, Osun" },
  { value: "Isokan_Osun", label: "Isokan, Osun" },
  { value: "Iwo_Osun", label: "Iwo, Osun" },
  { value: "Obokun_Osun", label: "Obokun, Osun" },
  { value: "Odo-Otin_Osun", label: "Odo-Otin, Osun" },
  { value: "Ola-Oluwa_Osun", label: "Ola-Oluwa, Osun" },
  { value: "Olorunda_Osun", label: "Olorunda, Osun" },
  { value: "Oriade_Osun", label: "Oriade, Osun" },
  { value: "Orolu_Osun", label: "Orolu, Osun" },
  { value: "Osogbo_Osun", label: "Osogbo, Osun" },
  { value: "Afijio_Oyo", label: "Afijio, Oyo" },
  { value: "Akinyele_Oyo", label: "Akinyele, Oyo" },
  { value: "Atiba_Oyo", label: "Atiba, Oyo" },
  { value: "Atisbo_Oyo", label: "Atisbo, Oyo" },
  { value: "Egbeda_Oyo", label: "Egbeda, Oyo" },
  { value: "Ibadan Central_Oyo", label: "Ibadan Central, Oyo" },
  { value: "Ibadan North_Oyo", label: "Ibadan North, Oyo" },
  { value: "Ibadan North West_Oyo", label: "Ibadan North West, Oyo" },
  { value: "Ibadan South East_Oyo", label: "Ibadan South East, Oyo" },
  { value: "Ibadan South West_Oyo", label: "Ibadan South West, Oyo" },
  { value: "Ibarapa Central_Oyo", label: "Ibarapa Central, Oyo" },
  { value: "Ibarapa East_Oyo", label: "Ibarapa East, Oyo" },
  { value: "Ibarapa North_Oyo", label: "Ibarapa North, Oyo" },
  { value: "Ido_Oyo", label: "Ido, Oyo" },
  { value: "Irepo_Oyo", label: "Irepo, Oyo" },
  { value: "Iseyin_Oyo", label: "Iseyin, Oyo" },
  { value: "Itesiwaju_Oyo", label: "Itesiwaju, Oyo" },
  { value: "Iwajowa_Oyo", label: "Iwajowa, Oyo" },
  { value: "Kajola_Oyo", label: "Kajola, Oyo" },
  { value: "Lagelu Ogbomosho North_Oyo", label: "Lagelu Ogbomosho North, Oyo" },
  { value: "Ogbomosho South_Oyo", label: "Ogbomosho South, Oyo" },
  { value: "Ogo Oluwa_Oyo", label: "Ogo Oluwa, Oyo" },
  { value: "Olorunsogo_Oyo", label: "Olorunsogo, Oyo" },
  { value: "Oluyole_Oyo", label: "Oluyole, Oyo" },
  { value: "Ona-Ara_Oyo", label: "Ona-Ara, Oyo" },
  { value: "Orelope_Oyo", label: "Orelope, Oyo" },
  { value: "Ori Ire_Oyo", label: "Ori Ire, Oyo" },
  { value: "Oyo East_Oyo", label: "Oyo East, Oyo" },
  { value: "Oyo West_Oyo", label: "Oyo West, Oyo" },
  { value: "Saki East_Oyo", label: "Saki East, Oyo" },
  { value: "Saki West_Oyo", label: "Saki West, Oyo" },
  { value: "Surulere_Oyo", label: "Surulere, Oyo" },
  { value: "Barikin Ladi_Plateau", label: "Barikin Ladi, Plateau" },
  { value: "Bassa_Plateau", label: "Bassa, Plateau" },
  { value: "Bokkos_Plateau", label: "Bokkos, Plateau" },
  { value: "Jos East_Plateau", label: "Jos East, Plateau" },
  { value: "Jos North_Plateau", label: "Jos North, Plateau" },
  { value: "Jos South_Plateau", label: "Jos South, Plateau" },
  { value: "Kanam_Plateau", label: "Kanam, Plateau" },
  { value: "Kanke_Plateau", label: "Kanke, Plateau" },
  { value: "Langtang North_Plateau", label: "Langtang North, Plateau" },
  { value: "Langtang South_Plateau", label: "Langtang South, Plateau" },
  { value: "Mangu_Plateau", label: "Mangu, Plateau" },
  { value: "Mikang_Plateau", label: "Mikang, Plateau" },
  { value: "Pankshin_Plateau", label: "Pankshin, Plateau" },
  { value: "Qua'an Pan_Plateau", label: "Qua'an Pan, Plateau" },
  { value: "Riyom_Plateau", label: "Riyom, Plateau" },
  { value: "Shendam_Plateau", label: "Shendam, Plateau" },
  { value: "Wase_Plateau", label: "Wase, Plateau" },
  { value: "Abua/Odual_Rivers", label: "Abua/Odual, Rivers" },
  { value: "Ahoada East_Rivers", label: "Ahoada East, Rivers" },
  { value: "Ahoada West_Rivers", label: "Ahoada West, Rivers" },
  { value: "Akuku Toru_Rivers", label: "Akuku Toru, Rivers" },
  { value: "Andoni_Rivers", label: "Andoni, Rivers" },
  { value: "Asari-Toru_Rivers", label: "Asari-Toru, Rivers" },
  { value: "Bonny_Rivers", label: "Bonny, Rivers" },
  { value: "Degema_Rivers", label: "Degema, Rivers" },
  { value: "Emohua_Rivers", label: "Emohua, Rivers" },
  { value: "Eleme_Rivers", label: "Eleme, Rivers" },
  { value: "Etche_Rivers", label: "Etche, Rivers" },
  { value: "Gokana_Rivers", label: "Gokana, Rivers" },
  { value: "Ikwerre_Rivers", label: "Ikwerre, Rivers" },
  { value: "Khana_Rivers", label: "Khana, Rivers" },
  { value: "Obio/Akpor_Rivers", label: "Obio/Akpor, Rivers" },
  { value: "Ogba/Egbema/Ndoni_Rivers", label: "Ogba/Egbema/Ndoni, Rivers" },
  { value: "Ogu/Bolo_Rivers", label: "Ogu/Bolo, Rivers" },
  { value: "Okrika_Rivers", label: "Okrika, Rivers" },
  { value: "Omumma_Rivers", label: "Omumma, Rivers" },
  { value: "Opobo/Nkoro_Rivers", label: "Opobo/Nkoro, Rivers" },
  { value: "Oyigbo_Rivers", label: "Oyigbo, Rivers" },
  { value: "Port-Harcourt_Rivers", label: "Port-Harcourt, Rivers" },
  { value: "Tai_Rivers", label: "Tai, Rivers" },
  { value: "Binji_Sokoto", label: "Binji, Sokoto" },
  { value: "Bodinga_Sokoto", label: "Bodinga, Sokoto" },
  { value: "Dange-shnsi_Sokoto", label: "Dange-shnsi, Sokoto" },
  { value: "Gada_Sokoto", label: "Gada, Sokoto" },
  { value: "Goronyo_Sokoto", label: "Goronyo, Sokoto" },
  { value: "Gudu_Sokoto", label: "Gudu, Sokoto" },
  { value: "Gawabawa_Sokoto", label: "Gawabawa, Sokoto" },
  { value: "Illela_Sokoto", label: "Illela, Sokoto" },
  { value: "Isa_Sokoto", label: "Isa, Sokoto" },
  { value: "Kware_Sokoto", label: "Kware, Sokoto" },
  { value: "kebbe_Sokoto", label: "kebbe, Sokoto" },
  { value: "Rabah_Sokoto", label: "Rabah, Sokoto" },
  { value: "Sabon birni_Sokoto", label: "Sabon birni, Sokoto" },
  { value: "Shagari_Sokoto", label: "Shagari, Sokoto" },
  { value: "Silame_Sokoto", label: "Silame, Sokoto" },
  { value: "Sokoto North_Sokoto", label: "Sokoto North, Sokoto" },
  { value: "Sokoto South_Sokoto", label: "Sokoto South, Sokoto" },
  { value: "Tambuwal_Sokoto", label: "Tambuwal, Sokoto" },
  { value: "Tqngaza_Sokoto", label: "Tqngaza, Sokoto" },
  { value: "Tureta_Sokoto", label: "Tureta, Sokoto" },
  { value: "Wamako_Sokoto", label: "Wamako, Sokoto" },
  { value: "Wurno_Sokoto", label: "Wurno, Sokoto" },
  { value: "Yabo_Sokoto", label: "Yabo, Sokoto" },
  { value: "Ardo-kola_Taraba", label: "Ardo-kola, Taraba" },
  { value: "Bali_Taraba", label: "Bali, Taraba" },
  { value: "Donga_Taraba", label: "Donga, Taraba" },
  { value: "Gashaka_Taraba", label: "Gashaka, Taraba" },
  { value: "Cassol_Taraba", label: "Cassol, Taraba" },
  { value: "Ibi_Taraba", label: "Ibi, Taraba" },
  { value: "Jalingo_Taraba", label: "Jalingo, Taraba" },
  { value: "Karin-Lamido_Taraba", label: "Karin-Lamido, Taraba" },
  { value: "Kurmi_Taraba", label: "Kurmi, Taraba" },
  { value: "Lau_Taraba", label: "Lau, Taraba" },
  { value: "Sardauna_Taraba", label: "Sardauna, Taraba" },
  { value: "Takum_Taraba", label: "Takum, Taraba" },
  { value: "Ussa_Taraba", label: "Ussa, Taraba" },
  { value: "Wukari_Taraba", label: "Wukari, Taraba" },
  { value: "Yorro_Taraba", label: "Yorro, Taraba" },
  { value: "Zing_Taraba", label: "Zing, Taraba" },
  { value: "Bade_Yobe", label: "Bade, Yobe" },
  { value: "Bursari_Yobe", label: "Bursari, Yobe" },
  { value: "Damaturu_Yobe", label: "Damaturu, Yobe" },
  { value: "Fika_Yobe", label: "Fika, Yobe" },
  { value: "Fune_Yobe", label: "Fune, Yobe" },
  { value: "Geidam_Yobe", label: "Geidam, Yobe" },
  { value: "Gujba_Yobe", label: "Gujba, Yobe" },
  { value: "Gulani_Yobe", label: "Gulani, Yobe" },
  { value: "Jakusko_Yobe", label: "Jakusko, Yobe" },
  { value: "Karasuwa_Yobe", label: "Karasuwa, Yobe" },
  { value: "Karawa_Yobe", label: "Karawa, Yobe" },
  { value: "Machina_Yobe", label: "Machina, Yobe" },
  { value: "Nangere_Yobe", label: "Nangere, Yobe" },
  { value: "Nguru Potiskum_Yobe", label: "Nguru Potiskum, Yobe" },
  { value: "Tarmua_Yobe", label: "Tarmua, Yobe" },
  { value: "Yunusari_Yobe", label: "Yunusari, Yobe" },
  { value: "Yusufari_Yobe", label: "Yusufari, Yobe" },
  { value: "Anka_Zamfara", label: "Anka, Zamfara" },
  { value: "Bakura_Zamfara", label: "Bakura, Zamfara" },
  { value: "Birnin Magaji_Zamfara", label: "Birnin Magaji, Zamfara" },
  { value: "Bukkuyum_Zamfara", label: "Bukkuyum, Zamfara" },
  { value: "Bungudu_Zamfara", label: "Bungudu, Zamfara" },
  { value: "Gummi_Zamfara", label: "Gummi, Zamfara" },
  { value: "Gusau_Zamfara", label: "Gusau, Zamfara" },
  { value: "Kaura_Zamfara", label: "Kaura, Zamfara" },
  { value: "Namoda_Zamfara", label: "Namoda, Zamfara" },
  { value: "Maradun_Zamfara", label: "Maradun, Zamfara" },
  { value: "Maru_Zamfara", label: "Maru, Zamfara" },
  { value: "Shinkafi_Zamfara", label: "Shinkafi, Zamfara" },
  { value: "Talata Mafara_Zamfara", label: "Talata Mafara, Zamfara" },
  { value: "Tsafe_Zamfara", label: "Tsafe, Zamfara" },
  { value: "Zurmi_Zamfara", label: "Zurmi, Zamfara" },
];
